name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
    - name: Install Valgrind
      run: |
        sudo apt-get update --fix-missing
        sudo apt install valgrind
        echo "Valgrind installed"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make vg
      run: make vg
#     - name: make distcheck
#       run: make distcheck
